/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package percobaan;

/**
 *
 * @author User
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.*;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    static String user;
    public home(String username ) {
        initComponents();
       dapatPembeli();
      totalOmset();
      totalBarang();
      tanggalan();
      this.setLocationRelativeTo(null);
      this.setResizable(false);
      this.user = username;
      
        setDashboardUsername();
    }
    private void setDashboardUsername(){
        this.username.setText(this.user);
    }
    private void tanggalan(){
        SimpleDateFormat format = new SimpleDateFormat("EEEE dd MMMM yyyy");
        java.util.Date date = new java.util.Date();
        tanggal.setText(format.format(date));
    }
    public void setName(String user){
    username.setText(user);
    }
public void dapatPembeli(){
    Calendar c = Calendar.getInstance();
    Date harisekarang = new Date();
            String dateParser = String.valueOf(c.get(Calendar.YEAR)) + "-" + String.valueOf(harisekarang.getMonth() + 1)
                    + "-" +String.valueOf(c.get(Calendar.DAY_OF_MONTH));
         String sql = "SELECT count(*) AS total_pembeli FROM transaksi WHERE YEAR(tanggal) = YEAR('" + dateParser + "' ) "  
                 +"AND MONTH (`tanggal`) = MONTH('" + dateParser + "') "
                 + "AND DAY(`tanggal`) = DAY('" + dateParser +"')";
         try {
             java.sql.Connection objConn = (Connection)koneksi.koneksi();
             java.sql.PreparedStatement prp = objConn.prepareStatement(sql);
             java.sql.ResultSet rs = prp.executeQuery(sql);
             while(rs.next()){
                 pembeli.setText(rs.getString("total_pembeli"));
             }  
         } catch(SQLException e){
             e.printStackTrace();
         }
}
public void totalOmset(){
    Calendar c = Calendar.getInstance();
    Date harisekarang = new Date();
            String dateParser = String.valueOf(c.get(Calendar.YEAR)) + "-" + String.valueOf(harisekarang.getMonth() + 1)
                    + "-" +String.valueOf(c.get(Calendar.DAY_OF_MONTH));
            String total = "SELECT SUM(`totalkeseluruhan`) as totalharian  FROM transaksi WHERE YEAR(tanggal) "
                    + "= YEAR('" + dateParser + "' ) "  
                 +"AND MONTH (`tanggal`) = MONTH('" + dateParser + "') "
                 + "AND DAY(`tanggal`) = DAY('" + dateParser +"')";
            try{
                java.sql.Connection Conn = (Connection)koneksi.koneksi();
             java.sql.PreparedStatement prp = Conn.prepareStatement(total);
             java.sql.ResultSet rs = prp.executeQuery(total);
             while(rs.next()){
                 omset.setText((rs.getString("totalharian")));
             }
            } catch (SQLException e){
             e.printStackTrace();
            }
}
public void totalBarang(){
    Calendar c = Calendar.getInstance();
    Date harisekarang = new Date();
            String dateParser = String.valueOf(c.get(Calendar.YEAR)) + "-" + String.valueOf(harisekarang.getMonth() + 1)
                    + "-" +String.valueOf(c.get(Calendar.DAY_OF_MONTH));
            String total = "SELECT SUM(`qty`) as totalbarang  FROM transaksi WHERE YEAR(tanggal) = YEAR('" + dateParser + "' ) "  
                 +"AND MONTH (`tanggal`) = MONTH('" + dateParser + "') "
                 + "AND DAY(`tanggal`) = DAY('" + dateParser +"')";
            try{
                java.sql.Connection Conn = (Connection)koneksi.koneksi();
             java.sql.PreparedStatement prp = Conn.prepareStatement(total);
             java.sql.ResultSet rs = prp.executeQuery(total);
             while(rs.next()){
                 barang.setText((rs.getString("totalbarang")));
             }
            } catch (SQLException e){
             e.printStackTrace();
            }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        pembeli = new javax.swing.JLabel();
        omset = new javax.swing.JLabel();
        barang = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText(" Hai");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 160, 20));

        pembeli.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pembeli.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 150, 50));

        omset.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        omset.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(omset, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 120, 40));

        barang.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        barang.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 60, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pembeli");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        tanggal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setText("jLabel5");
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(111, 4, 45));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lihat");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 180, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Diagram");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Terjual");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, -1));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 40));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 40));

        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, 40));

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 423, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/percobaan/10000.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT tanggal, totalkeseluruhan FROM transaksi";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(koneksi.koneksi(),sql);
            JFreeChart chart=ChartFactory.createLineChart("Diagram Penghasilan","tanggal", 
                    "totalkeselurhan",  dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot=null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Diagram Penghasilan", chart);
            frame.setVisible(true);
            frame.setSize(400,650);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new barang(user).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new barang(this.user).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new supplier(this.user).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel omset;
    private javax.swing.JLabel pembeli;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
