/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package percobaan;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
        tabel();
        totalhasil();
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        txttgl1 = new javax.swing.JTextField();
        txttgl2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 820, 310));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 100, 40));

        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 100, 40));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 50, 40));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 120, 40));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 130, 40));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 80, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 190, 30));
        getContentPane().add(txttgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 40, 30));
        getContentPane().add(txttgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/percobaan/1000013.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void totalhasil(){
        try{
            String totalduit = "SELECT SUM(`totalkeseluruhan`) as totaluang FROM transaksi";
            java.sql.Connection Conn =(Connection) koneksi.koneksi();
            java.sql.Statement stm = Conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(totalduit);
             DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
            while(rs.next()){
                koneksi obj = new koneksi();
                total.setText((rs.getString("totaluang")));
                total.setText(String.valueOf(rs.getString(3)));
            }
            
        } catch (Exception e){
            
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // untuk mengexport data ke excel
         openSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
                    new laporan().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    
 tabelku();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void tabelku(){
        //laporan perbulan
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("qty");
        model.addColumn("Total Keseluruhan");
       

    String tampilan = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
    System.out.println(fm);
   String tgl1 = String.valueOf(fm.format(jDateChooser1.getDate()));
    String tgl2 = String.valueOf(fm.format(jDateChooser2.getDate()));
        
        try {
            int no =1;
            int IdTransaksi =0;
            int Tanggal=0;
            int qty =0;
            int TotalKeseluruhan =0;
            int IdBarang =0;
            String sql ="SELECT * From transaksi where tanggal  BETWEEN  '"+tgl1+"' AND '"+tgl2+"'";
            System.out.println(sql);
            java.sql.Connection conn = (Connection) koneksi.koneksi();
            java.sql.Statement stm =conn.createStatement();
            java.sql.ResultSet res =stm.executeQuery(sql);
            while(res.next()){
                 DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        String idr = kursIndonesia.format(Integer.parseInt(String.valueOf(res.getString(3))));
                 model.addRow(new Object[] {no++,res.getString(1),res.getString(2), 
            res.getString(3), idr});
                
            }
           jTable1.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
     private void tabel(){
         //memasukkan ketabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("qty");
        model.addColumn("Total Keseluruhan");
      
        
        
        try {
            int no =1;
            int IdTransaksi =0;
            int Tanggal=0;
            int qty =0;
            int TotalKeseluruhan =0;
            
            String sql ="SELECT*From transaksi";
            java.sql.Connection conn = (Connection) koneksi.koneksi();
            java.sql.Statement stm =conn.createStatement();
            java.sql.ResultSet res =stm.executeQuery(sql);
            while(res.next()){
                DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        String idr = kursIndonesia.format(Integer.parseInt(String.valueOf(res.getString(4))));
                 model.addRow(new Object[] {no++,res.getString(1),res.getString(2), 
            res.getString(3), idr});
                
            }
           jTable1.setModel(model);
        } catch(Exception e){
            e.printStackTrace();
        }}
     
     public void RubahkeExcel(javax.swing.JTable table, File file){
         //export ke excel
         try{
             DefaultTableModel Model_Data = (DefaultTableModel)table.getModel();
             FileWriter ObjWriter = new FileWriter(file);
             System.out.println(file.toString());
             for(int i =0; i < Model_Data.getColumnCount(); i++){
                 System.out.println(Model_Data.getColumnName(i));
                 ObjWriter.write(Model_Data.getColumnName(i) + "\t");      
             } ObjWriter.write("\n");
             for(int i =0; i < Model_Data.getRowCount(); i++){
                 for(int j=0; j<Model_Data.getColumnCount(); j++){
                     ObjWriter.write(Model_Data.getValueAt(i, j).toString()+ "\t");
                 } ObjWriter.write("\n");
             }
             ObjWriter.close();
         } catch(IOException e){
             System.out.println(e);
         }
}
       public void openSelection(){
         JFileChooser path = new JFileChooser();
         path.showOpenDialog(this);
         String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
         try{
             File f = path.getSelectedFile();
             String location = f.getAbsolutePath();
             String filename = location + "_"+".xls";
             JOptionPane.showMessageDialog(null, filename);
             File fp = new File(filename);
             
             RubahkeExcel(jTable1, fp);
             JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
         } catch (Exception e){
           e.printStackTrace();
         }
     }
     private void print(){
         try{
             jTable1.print();
         } catch (Exception e){
             JOptionPane.showMessageDialog(null, "Data Kosong!");
         }
     }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txttgl1;
    private javax.swing.JTextField txttgl2;
    // End of variables declaration//GEN-END:variables
}
